AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  SourceBucketName:
    Type: String
    Description: The name of the source S3 bucket.
  
  DestinationBucketName:
    Type: String
    Description: The name of the destination S3 bucket.

  LambdaCodeBucketName:
    Type: String
    Description: The name of the S3 bucket to store the Lambda function zip file.

Resources:
  
  SourceBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref SourceBucketName
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: 's3:ObjectCreated:*'
            Function: !GetAtt S3CopyLambda.Arn

  DestinationBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref DestinationBucketName

  LambdaExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service: 'lambda.amazonaws.com'
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: 'S3CopyPolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action:
                  - 's3:GetObject'
                Resource: !Sub 'arn:aws:s3:::${SourceBucketName}/*'
              - Effect: 'Allow'
                Action:
                  - 's3:PutObject'
                Resource: !Sub 'arn:aws:s3:::${DestinationBucketName}/*'

  
  S3CopyLambda:
    Type: 'AWS::Lambda::Function'
    Properties:
      Handler: 'lambda.lambda_handler'
      Role: !GetAtt LambdaExecutionRole.Arn
      FunctionName: 'S1CopyFunction'
      Runtime: 'python3.8'
      Code:
        S3Bucket: !Ref LambdaCodeBucketName  
        S3Key: 'lambda.zip'            
      Environment:
        Variables:
          SOURCE_BUCKET: !Ref SourceBucketName
          DEST_BUCKET: !Ref DestinationBucketName


  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref S3CopyLambda
      Action: 'lambda:InvokeFunction'
      Principal: 's3.amazonaws.com'
      SourceArn: !Sub 'arn:aws:s3:::${SourceBucketName}'
